version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    volumes:
      - .:/app
      - static_files:/static/
  nginx:
    build:
      context: ./compose/nginx/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 80:80
    links:
      - app:app
    volumes:
      - static_files:/static/
    depends_on:
      - app

volumes:
  static_files:
